name: mobileworm
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  mobileworm:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Mobileworm
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sangfroyd.mobileworm
        PRODUCT_NAME: EarWorm
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: SX55QKAFL4
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: EarWorm
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.music
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        SUPPORTS_MACCATALYST: NO
