name: mobileworm
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  mobileworm:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Mobileworm
    info:
      path: Mobileworm/Info.plist
      properties:
        CFBundleDisplayName: EarWorm
        LSApplicationCategoryType: public.app-category.music
        LSSupportsOpeningDocumentsInPlace: true
        UIBackgroundModes:
          - audio
        UIApplicationSupportsIndirectInputEvents: true
        UIFileSharingEnabled: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations~iphone:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sangfroyd.mobileworm
        PRODUCT_NAME: EarWorm
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: SX55QKAFL4
        SUPPORTS_MACCATALYST: NO
